#!/usr/bin/env node
/**
 * Cena Color System v2 — generator
 *
 * Reads family-source.json (mirror of _tokens/color-system-v2.md §3 + §3b),
 * computes 11-stop OKLCH-in-P3 ramps per family via linear-in-L interpolation
 * (per spec §1.4), emits CSS custom properties as primary OKLCH declarations
 * with sRGB hex fallbacks for legacy/edge contexts.
 *
 * Output: ../../_tokens/generated/palette.css (canonical) and
 *         a haven-ui-shaped copy ready to drop into
 *         haven-ui/packages/design-system/src/styles/tokens/palette.css
 *
 * Architecture: every family is defined by exactly three OKLCH triplets
 * (root, max, min). Stops 50-400 interpolate between root and max;
 * stops 600-950 interpolate between root and min; stop 500 = root.
 *
 * Position-to-weight mapping (linear-in-L, k=1):
 *   Stop 50  = 100% max
 *   Stop 100 = 80% max + 20% root
 *   Stop 200 = 60% max + 40% root
 *   Stop 300 = 40% max + 60% root
 *   Stop 400 = 20% max + 80% root
 *   Stop 500 = 100% root (= 0% anchor)
 *   Stop 600 = 80% root + 20% min
 *   Stop 700 = 60% root + 40% min
 *   Stop 800 = 40% root + 60% min
 *   Stop 900 = 20% root + 80% min
 *   Stop 950 = 100% min
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  parse,
  formatHex,
  oklch,
  interpolate,
  converter,
} from 'culori';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ---------- Source loading ----------

const sourcePath = resolve(__dirname, 'family-source.json');
const source = JSON.parse(readFileSync(sourcePath, 'utf8'));

const STOPS = [
  { stop: 50,  anchor: 'max', mix: 1.0 },
  { stop: 100, anchor: 'max', mix: 0.8 },
  { stop: 200, anchor: 'max', mix: 0.6 },
  { stop: 300, anchor: 'max', mix: 0.4 },
  { stop: 400, anchor: 'max', mix: 0.2 },
  { stop: 500, anchor: 'root', mix: 0.0 },
  { stop: 600, anchor: 'min', mix: 0.2 },
  { stop: 700, anchor: 'min', mix: 0.4 },
  { stop: 800, anchor: 'min', mix: 0.6 },
  { stop: 900, anchor: 'min', mix: 0.8 },
  { stop: 950, anchor: 'min', mix: 1.0 },
];

// ---------- Interpolation ----------

const toOklch = converter('oklch');

function parseOklch(str) {
  const color = parse(str);
  if (!color) throw new Error(`culori failed to parse: ${str}`);
  return toOklch(color);
}

function mixOklch(rootColor, anchorColor, anchorWeight) {
  // anchorWeight = 1.0 means 100% anchor (pure max or min); 0 means pure root.
  // Linear interpolation in OKLCH space — equal L-delta per step.
  const interp = interpolate([rootColor, anchorColor], 'oklch');
  return interp(anchorWeight);
}

function computeStop(family, stopSpec) {
  const root = parseOklch(family.root);
  if (stopSpec.anchor === 'root') return root;
  const anchorStr = family[stopSpec.anchor];
  const anchor = parseOklch(anchorStr);
  return mixOklch(root, anchor, stopSpec.mix);
}

// ---------- Emission ----------

function fmtOklch(c) {
  const L = (c.l * 100).toFixed(2);
  const C = (c.c ?? 0).toFixed(4);
  // Hue may be undefined for achromatic colors near sRGB neutral; default 0.
  const H = (c.h ?? 0).toFixed(2);
  return `oklch(${L}% ${C} ${H})`;
}

function fmtHexFallback(c) {
  // formatHex returns sRGB-clipped hex; P3 colors outside sRGB will be
  // gamut-mapped to nearest sRGB by culori's default.
  return formatHex(c) || '#000000';
}

function emitFamily(name, family) {
  const lines = [];
  lines.push(`  /* ${name} — ${family.role} */`);
  for (const stopSpec of STOPS) {
    const c = computeStop(family, stopSpec);
    const oklchStr = fmtOklch(c);
    const hexStr = fmtHexFallback(c);
    lines.push(`  --color-${name}-${stopSpec.stop}: ${oklchStr};`);
    lines.push(`  --color-${name}-${stopSpec.stop}-hex: ${hexStr};`);
  }
  return lines.join('\n');
}

function emitLogoIdentity() {
  const lines = [];
  lines.push('  /* Logo identity tokens — hex-frozen per spec §5; never computed. */');
  for (const [name, entry] of Object.entries(source.logo_identity)) {
    if (name.startsWith('$') || name === 'comment') continue;
    lines.push(`  --logo-${name}: ${entry.hex};  /* ${entry.role} */`);
  }
  return lines.join('\n');
}

function emit() {
  const header = `/**
 * Cena Color System v2 — generated palette.css
 *
 * Generated by tools/color-generator/generate.mjs from family-source.json.
 * DO NOT EDIT THIS FILE BY HAND — re-run the generator instead.
 *
 * Architecture: spec §1 (root/max/min + linear-in-L interpolation).
 * Family set:   spec §2 (16 Tailwind hue families + sage + sand = 18 active).
 * Output:       OKLCH-in-P3 primary + sRGB hex fallback (-hex suffix).
 *
 * Generated: ${new Date().toISOString().slice(0, 10)}
 * Source version: ${source.$version}
 * Direction: ${source.$direction} (50 = lightest, 950 = darkest)
 */

:root {
${emitLogoIdentity()}

`;

  const familyBlocks = [];
  for (const [name, family] of Object.entries(source.families)) {
    familyBlocks.push(emitFamily(name, family));
  }

  const footer = `\n}\n`;

  return header + familyBlocks.join('\n\n') + footer;
}

// ---------- Validation ----------

function validate(output) {
  const issues = [];

  // Check 1: every active family has 11 stops × 2 declarations (oklch + hex)
  for (const name of Object.keys(source.families)) {
    for (const stopSpec of STOPS) {
      const oklchToken = `--color-${name}-${stopSpec.stop}:`;
      const hexToken = `--color-${name}-${stopSpec.stop}-hex:`;
      if (!output.includes(oklchToken)) issues.push(`missing ${oklchToken}`);
      if (!output.includes(hexToken)) issues.push(`missing ${hexToken}`);
    }
  }

  // Check 2: logo identity tokens present
  for (const name of Object.keys(source.logo_identity)) {
    if (name.startsWith('$') || name === 'comment') continue;
    const token = `--logo-${name}:`;
    if (!output.includes(token)) issues.push(`missing ${token}`);
  }

  // Check 3: no L > 100 in any computed OKLCH (out-of-range)
  const lValues = [...output.matchAll(/oklch\(([\d.]+)%/g)].map(m => parseFloat(m[1]));
  for (const L of lValues) {
    if (L > 100 || L < 0) issues.push(`out-of-range L value: ${L}%`);
  }

  return issues;
}

// ---------- Main ----------

function main() {
  console.log(`Cena Color System v2 — generator`);
  console.log(`Source: ${sourcePath}`);
  console.log(`Active families: ${Object.keys(source.families).length}`);
  console.log(`Stops per family: ${STOPS.length}`);
  console.log('');

  const output = emit();

  const issues = validate(output);
  if (issues.length > 0) {
    console.error(`Validation failed with ${issues.length} issue(s):`);
    for (const issue of issues) console.error(`  - ${issue}`);
    process.exit(1);
  }

  const outDir = resolve(__dirname, '../../_tokens/generated');
  mkdirSync(outDir, { recursive: true });
  const outPath = resolve(outDir, 'palette.css');
  writeFileSync(outPath, output);
  console.log(`Wrote ${outPath} (${output.length} bytes)`);

  const stopsCount = Object.keys(source.families).length * STOPS.length;
  console.log(`Generated ${stopsCount} family stops + ${Object.keys(source.logo_identity).filter(k => !k.startsWith('$') && k !== 'comment').length} logo identity tokens`);
  console.log('Validation: OK');
}

main();
